Region: us-east-1
Image:
  Os: ubuntu2404
  CustomAmi: ami-08ea421ec9fad0a09

HeadNode:
  InstanceType: c5.large
  Ssh:
    KeyName: dzhang # <-- change to your keypair name
  Networking:
    SubnetId: subnet-074660a6fc92af350
    SecurityGroups:
      - sg-0f504cd36a5dc0b34

Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: ondemand
      CapacityType: ONDEMAND
      Networking:
        SubnetIds:
          - subnet-074660a6fc92af350
        SecurityGroups:
          - sg-0f504cd36a5dc0b34
      ComputeResources:
        - Name: c8a24xl
          InstanceType: c8a.24xlarge
          MinCount: 0
          MaxCount: 20

    - Name: spot
      CapacityType: SPOT
      Networking:
        SubnetIds:
          - subnet-074660a6fc92af350
        SecurityGroups:
          - sg-0f504cd36a5dc0b34
      ComputeResources:
        - Name: c8a24xl
          InstanceType: c8a.24xlarge
          MinCount: 0
          MaxCount: 50
 
    - Name: submit
      CapacityType: ONDEMAND
      Networking:
        SubnetIds:
          - subnet-074660a6fc92af350
        SecurityGroups:
          - sg-0f504cd36a5dc0b34
      ComputeResources:
        - Name: c8a2xl
          InstanceType: c8a.2xlarge
          MinCount: 0
          MaxCount: 2

SharedStorage:
  - Name: fsx_input
    StorageType: FsxLustre
    MountDir: /fsx_input
    FsxLustreSettings:
      FileSystemId: fs-03e9bfee5ab98c762
