Region: us-east-1
Image:
  Os: alinux2023
  CustomAmi: ami-0b93cb405ecdb5452

HeadNode:
  InstanceType: c5.large
  Ssh:
    KeyName: dzhang # <-- change to your keypair name
  Networking:
    SubnetId: subnet-074660a6fc92af350
    AdditionalSecurityGroups:
      - sg-0f504cd36a5dc0b34

Scheduling:
  Scheduler: slurm
  SlurmSettings:
    QueueUpdateStrategy: DRAIN
  SlurmQueues:
    - Name: ondemand-24xl
      CapacityType: ONDEMAND
      AllocationStrategy: lowest-price
      Networking:
        SubnetIds:
          - subnet-074660a6fc92af350
        AdditionalSecurityGroups:
          - sg-0f504cd36a5dc0b34
      ComputeResources:
        - Name: cpu24xl
          Instances:
            - InstanceType: c5.24xlarge
            - InstanceType: c6i.24xlarge
            - InstanceType: c7i.24xlarge
            - InstanceType: c8i.24xlarge
          MinCount: 0
          MaxCount: 20
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: false

    - Name: spot-24xl
      CapacityType: SPOT
      AllocationStrategy: capacity-optimized
      Networking:
        SubnetIds:
          - subnet-074660a6fc92af350
        AdditionalSecurityGroups:
          - sg-0f504cd36a5dc0b34
      ComputeResources:
        - Name: cpu24xl
          Instances:
            - InstanceType: c5.24xlarge
            - InstanceType: c6i.24xlarge
            - InstanceType: c7i.24xlarge
            - InstanceType: c8i.24xlarge
          MinCount: 0
          MaxCount: 50
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: false
 
    - Name: submit-2xl
      CapacityType: ONDEMAND
      AllocationStrategy: lowest-price
      Networking:
        SubnetIds:
          - subnet-074660a6fc92af350
        AdditionalSecurityGroups:
          - sg-0f504cd36a5dc0b34
      ComputeResources:
        - Name: cpu2xl
          Instances:
            - InstanceType: c5.2xlarge
            - InstanceType: c6i.2xlarge
            - InstanceType: c7i.2xlarge
            - InstanceType: c8i.2xlarge
          MinCount: 0
          MaxCount: 10
          DisableSimultaneousMultithreading: true  # disable hyperthreading (recommended)
          Efa:
            Enabled: false

SharedStorage:
  - Name: fsx_input
    StorageType: FsxLustre
    MountDir: /fsx_input
    FsxLustreSettings:
      FileSystemId: fs-03e9bfee5ab98c762
